# Credit Metrics

## Introduction

CreditMetrics was developed by J.P Morgan in 1997 and is used as a tool for accessing portfolio risk due to changes in debt value caused by changes in credit quality. CreditMetrics is a framework that enables business owners to quantify the impact of credit risk on the value of their portfolios and assess risk.



### Approach

1. Identify the credit-sensitive instruments in the portfolio. These are instruments whose value depends on the creditworthiness of a counterparty or debtor. Examples of credit-sensitive instruments are loans, bonds, credit default swaps and other derivatives.

2. Assign a credit rating to each counterparty or obligor. A credit rating is a measure of the probability of default or downgrade of a counterparty or obligor, based on historical data and expert judgement. Credit ratings are usually expressed in letter grades such as AAA, AA, A, BBB, BB, B, CCC, CC, C and D. The lower the rating, the higher the probability of default. The lower the rating, the higher the risk of default or downgrade.

3. Estimate the transition matrix and recovery rate for each rating category. A transition matrix is a table that shows the probability of a counterparty or obligor moving from one rating category to another over a given time horizon, such as one year. A recovery rate is the percentage of an instrument's face value that can be recovered in the event of a default or downgrade. For example, if a bond with a nominal value of USD 100 defaults and the bondholder recovers USD 40, the recovery rate is 40%.

4. Simulate the future credit ratings and values of the credit-sensitive instruments in the portfolio. Using the transition matrix and recovery rate, CreditMetrics can create scenarios of possible future credit ratings and values of the credit-sensitive instruments in the portfolio, taking into account the correlations between them. Correlations are measures of how the credit quality of different counterparties or debtors tends to develop together. For example, if two counterparties or obligors are in the same industry or region, there may be a positive correlation, meaning that their credit quality tends to improve or deteriorate together.

5. Calculate the credit value at risk (CVaR) and the credit value distribution of the portfolio. CVaR is a measure of the potential loss in value of the portfolio due to credit risk over a given time horizon and confidence level. For example, a CVaR of USD 10 million at a 95% confidence level over one year means that there is a 5% probability that the portfolio will lose more than USD 10 million in value over one year due to credit risk. The credit value distribution is a chart that shows the probability of different losses or gains in the value of the portfolio due to credit risk.

6. Analyse the sources and drivers of credit risk in the portfolio. CreditMetrics can provide various reports and statistics to help business owners understand the sources and drivers of credit risk in their portfolio, such as the contribution of each instrument, counterparty or rating category to CVaR and credit value distribution, as well as the sensitivity of portfolio value to changes in credit ratings, recovery rates or correlations, and the diversification benefits of adding or removing instruments or counterparties from the portfolio.

7. Implement strategies to mitigate or hedge credit risk in the portfolio. Based on the credit risk analysis, entrepreneurs can implement strategies to mitigate or hedge the credit risk in their portfolio, such as adjusting the portfolio composition, diversifying the portfolio across different instruments, counterparties or rating categories, transferring the credit risk to third parties, e.g. insurers or guarantors, or using credit derivatives such as credit default swaps to hedge against certain credit events.

### Assumptions

#### Distribution of credit ratings and assets: 
CreditMetrics assumes that the portfolio's credit ratings and assets follow a normal distribution (or lognormal distribution), which means that extreme events are rare and symmetric. In reality, however, credit ratings and assets can exhibit fat tails, skewness and correlation, meaning that extreme events are more likely and asymmetric. During the 2008 financial crisis, for example, many assets experienced significant downgrades and losses that were not captured by the normal distribution. To address this limitation, CreditMetrics can be modified to use alternative distributions that better reflect the empirical characteristics of credit risk, such as the Student-T distribution or the skewed normal distribution.

#### Transition matrix and the recovery rate: 
CreditMetrics uses a transition matrix to estimate the probability that an asset will move from one credit rating to another over a given time horizon. In addition, a recovery rate is used to estimate the percentage of the asset that can be recovered in the event of default. However, these parameters are not constant and can vary depending on the economic cycle, sector and issuer. For example, during a recession, the transition matrix may show a higher probability of downgrades and defaults and the recovery rate may be below average. To address this limitation, CreditMetrics can be modified to use dynamic transition matrices and recovery rates that reflect current and expected market conditions, such as macroeconomic factors, industry outlook and issuer-specific information.

##  Implementation approach

The process of asset value changes of the company determines its creditworthiness and defaults
- The model links asset value changes to credit rating changes and explains how the firm value-based model is parameterised
- The value of a company's assets determines its ability to pay its debtors
- We assume that there are a number of tiers to the asset value that determine a company's credit rating at the end of the period
- The percentage changes in asset value are normally distributed and parameterised by a mean $\mu$ and a standard deviation $/delta$ (not the volatility of the value of a credit instrument - the volatility of the return on assets for a given name)
- There are threshold values for the return on assets $𝑍_{𝐷EF}$, $𝑍_{𝐶𝐶𝐶}$, $𝑍_{𝐵𝐵𝐵}$, etc., so that if $𝑟_𝑘 < 𝑍𝐷𝑒𝑓$, then the debitor defaults, if $𝑍_{𝐷EF}<$𝑟_𝑘<𝑍_{𝐶𝐶𝐶}$, then the debitor is downgraded to CCC
- Modelling the return on an asset:
$$r_k=pY+\sqrt{1-p^2}Z_k$$

![alt text](CreditMetrics.png "Title")

## Basic Assumptions
- Number N of creditworthiness classes (or rating classes)
- Bond prices are constant within a rating class
- Loss is quantified by a change in credit rating for the period T1=1 (e.g. one year)
- Losses result exclusively from changes in creditworthiness - losses due to changes in market prices are not considered

### Import Librarieres für RiVaPy Test

In [1]:
import sys
sys.path.append("../..")

In [2]:
import rivapy
import pandas as pd
import numpy as np
import plotly.express as px

c:\Users\Anwender\source\repos\RiVaPy\notebooks\credit\../..\rivapy\__init__.py:13: UserWarning: The pyvacon module is not available. You may not use all functionality without this module. Consider installing pyvacon.
  warnings.warn("The pyvacon module is not available. You may not use all functionality without this module. Consider installing pyvacon.")


In [3]:
np.set_printoptions(formatter={'float': '{: 0.5f}'.format})

## Required test data

### Transition matrix

In [4]:
# User inputs
TransMat = np.matrix("""
90.81, 8.33, 0.68, 0.06, 0.08, 0.02, 0.01, 0.01;
0.70, 90.65, 7.79, 0.64, 0.06, 0.13, 0.02, 0.01;
0.09, 2.27, 91.05, 5.52, 0.74, 0.26, 0.01, 0.06;
0.02, 0.33, 5.95, 85.93, 5.30, 1.17, 1.12, 0.18;
0.03, 0.14, 0.67, 7.73, 80.53, 8.84, 1.00, 1.06;
0.01, 0.11, 0.24, 0.43, 6.48, 83.46, 4.07, 5.20;
0.21, 0, 0.22, 1.30, 2.38, 11.24, 64.86, 19.79""")/100

### Load position and issuer data

In [5]:
# folder_excel = "C:/Users/Noah Köstner/OneDrive - RIVACON GmbH/CreditModel_data/"
folder_excel = "C:/Users/Anwender/Desktop/"


In [6]:
from rivapy.instruments.components import Issuer
from scipy.stats import norm

excel_file = "Datenmodell_Krediportfoliomodell.xlsx"
positions = pd.read_excel(folder_excel + excel_file, "Positions")
issuer = pd.read_excel(folder_excel + excel_file, "Issuer")
issuer_list = []
for _, row in issuer.iterrows():
    issuer_list.append(
        Issuer(
            obj_id=row['IssuerID'],
            name=row['IssuerName'],
            rating=row['Rating'],
            country=row['Land'],
            sector=row['Branche'],
            esg_rating=row['ESG_Rating'] if 'ESG_Rating' in row else "AAA",
        )
    )

In [7]:
issuer_list[0].rating

'AA'

### Specifications

In [8]:
Nsim = 5000 # num sim for CVaR
r = 0 # risk free rate
t= 1
recoveryRate= 0.55
confidenceLevel = 5 #in percent
seed = 4 #seed for random number generation

### Read market data

In [9]:
dax_file = "^GDAXI.xlsx"
marketDataDAX = pd.read_excel(folder_excel + dax_file, "DAX").rename(columns={"Close" : "Dax"})
marketDataBASF = pd.read_excel(folder_excel + dax_file, "BASF").rename(columns={"Close" : "BASF"})
marketDataLHA = pd.read_excel(folder_excel + dax_file, "Lufthansa").rename(columns={"Close" : "LHA"})
marketDataVW = pd.read_excel(folder_excel + dax_file, "Volkswagen").rename(columns={"Close" : "VW"})
marketDataDAX = marketDataDAX[marketDataDAX["Date"]>='2007-04-02']
mergedData = marketDataDAX[['Date', 'Dax']].merge(marketDataBASF[['Date', 'BASF']], on='Date', how='left').merge(marketDataLHA[['Date', 'LHA']], on='Date', how='left').merge(marketDataVW[['Date', 'VW']], on='Date', how='left')

### Utilisation of credit metrics model within RiVaPy

#### Initialize Class

In [10]:
credit_metrics_object = rivapy.credit.creditMetricsModel(Nsim, TransMat, positions, issuer_list, mergedData, r, t, confidenceLevel, seed)

#### Calculate VaR

In [11]:
print(credit_metrics_object.position_data.head())

   InstrumentID InstrumentName  Exposure  IssuerID  Maturity  RecoveryRate
0             1   Instrument_1    100000         1         1           0.3
1             2   Instrument_2    200000         1         2           0.4
2             3   Instrument_3    300000         2         3           0.3
3             4   Instrument_4    300000         2         3           0.4
4             5   Instrument_5    300000         3         3           0.3


In [12]:
credit_metrics_object.get_issuer_groups()

,IssuerID,IssuerName,RecoveryRate,Rating,RatingID,Exposure
0,1,BASF,0.3,AA,1,100000
1,1,BASF,0.4,AA,1,400000
2,2,LHA,0.3,B,5,300000
3,2,LHA,0.4,B,5,300000
4,3,VW,0.3,A,2,300000
5,3,VW,0.4,A,2,900000
6,3,VW,0.5,A,2,300000


In [13]:
df = credit_metrics_object.get_expected_value()
print(df)
print(credit_metrics_object.get_issuer_groups())

               EV
issuer           
BASF     499969.0
LHA      579720.0
VW      1499460.0
   IssuerID IssuerName  RecoveryRate Rating  RatingID  Exposure
0         1       BASF           0.3     AA         1    100000
1         1       BASF           0.4     AA         1    400000
2         2        LHA           0.3      B         5    300000
3         2        LHA           0.4      B         5    300000
4         3         VW           0.3      A         2    300000
5         3         VW           0.4      A         2    900000
6         3         VW           0.5      A         2    300000


In [14]:
positions = credit_metrics_object.get_issuer_groups()
exposure = np.matrix(positions["Exposure"]).T
idx = positions["RatingID"]
LGD = 1 - positions["RecoveryRate"]
print(LGD)
print(idx)

0    0.7
1    0.6
2    0.7
3    0.6
4    0.7
5    0.6
6    0.5
Name: RecoveryRate, dtype: float64
0    1
1    1
2    5
3    5
4    2
5    2
6    2
Name: RatingID, dtype: int64


In [15]:
PD_t = credit_metrics_object.transition_matrix[:, -1]
PD_vec = PD_t[idx]
print(PD_vec)
LGD_np = LGD.to_numpy().reshape(-1, 1)
print(LGD_np)
-np.log(1 - np.multiply(LGD_np, PD_vec))

[[ 0.00010]
 [ 0.00010]
 [ 0.05200]
 [ 0.05200]
 [ 0.00060]
 [ 0.00060]
 [ 0.00060]]
[[ 0.70000]
 [ 0.60000]
 [ 0.70000]
 [ 0.60000]
 [ 0.70000]
 [ 0.60000]
 [ 0.50000]]


matrix([[ 0.00007],
        [ 0.00006],
        [ 0.03708],
        [ 0.03170],
        [ 0.00042],
        [ 0.00036],
        [ 0.00030]])

In [16]:
positions = credit_metrics_object.get_issuer_groups()
exposure = np.matrix(positions["Exposure"]).T
exposure

matrix([[100000],
        [400000],
        [300000],
        [300000],
        [300000],
        [900000],
        [300000]])

In [17]:
# df_test = credit_metrics_object.get_expected_value()
# df_test = credit_metrics_object.get_issuer_groups()
get_states = credit_metrics_object.get_states()

In [18]:
print(get_states)

               D          C          B         BB        BBB          A  \
issuer                                                                    
BASF    190000.0   438651.0   483880.0   496714.0   499442.0   499814.0   
LHA     210000.0   522819.0   579720.0   595866.0   599298.0   599766.0   
VW      600000.0  1321890.0  1453200.0  1490460.0  1498380.0  1499460.0   

               AA        AAA  
issuer                        
BASF     499969.0   499969.0  
LHA      599961.0   599961.0  
VW      1499910.0  1499910.0  


In [19]:
print(np.cumsum(np.flipud(credit_metrics_object.transition_matrix.T), 0))

[[ 0.00010  0.00010  0.00060  0.00180  0.01060  0.05200  0.19790]
 [ 0.00020  0.00030  0.00070  0.01300  0.02060  0.09270  0.84650]
 [ 0.00040  0.00160  0.00330  0.02470  0.10900  0.92730  0.95890]
 [ 0.00120  0.00220  0.01070  0.07770  0.91430  0.99210  0.98270]
 [ 0.00180  0.00860  0.06590  0.93700  0.99160  0.99640  0.99570]
 [ 0.00860  0.08650  0.97640  0.99650  0.99830  0.99880  0.99790]
 [ 0.09190  0.99300  0.99910  0.99980  0.99970  0.99990  0.99790]
 [ 1.00000  1.00000  1.00000  1.00000  1.00000  1.00000  1.00000]]


In [20]:
Z = np.cumsum(np.flipud(credit_metrics_object.transition_matrix.T), 0)
Z[Z >= (1 - 1 / 1e12)] = 1 - 1 / 1e12
Z[Z <= (0 + 1 / 1e12)] = 0 + 1 / 1e12

print(Z)

CutOffs = norm.ppf(Z, 0, 1)  
print(CutOffs)

[[ 0.00010  0.00010  0.00060  0.00180  0.01060  0.05200  0.19790]
 [ 0.00020  0.00030  0.00070  0.01300  0.02060  0.09270  0.84650]
 [ 0.00040  0.00160  0.00330  0.02470  0.10900  0.92730  0.95890]
 [ 0.00120  0.00220  0.01070  0.07770  0.91430  0.99210  0.98270]
 [ 0.00180  0.00860  0.06590  0.93700  0.99160  0.99640  0.99570]
 [ 0.00860  0.08650  0.97640  0.99650  0.99830  0.99880  0.99790]
 [ 0.09190  0.99300  0.99910  0.99980  0.99970  0.99990  0.99790]
 [ 1.00000  1.00000  1.00000  1.00000  1.00000  1.00000  1.00000]]
[[-3.71902 -3.71902 -3.23888 -2.91124 -2.30440 -1.62576 -0.84915]
 [-3.54008 -3.43161 -3.19465 -2.22621 -2.04151 -1.32431  1.02154]
 [-3.35279 -2.94784 -2.71638 -1.96512 -1.23186  1.45597  1.73806]
 [-3.03567 -2.84796 -2.30085 -1.42071  1.36772  2.41350  2.11301]
 [-2.91124 -2.38240 -1.50704  1.53007  2.39106  2.68745  2.62756]
 [-2.38240 -1.36263  1.98450  2.69684  2.92905  3.03567  2.86274]
 [-1.32915  2.45726  3.12139  3.54008  3.43161  3.71902  2.86274]
 [ 7.0344

In [40]:
EV = credit_metrics_object.get_expected_value()
print(EV)
states = credit_metrics_object.get_states()
print(states)
correlation = credit_metrics_object.get_correlation()
print(correlation)
CutOffs = credit_metrics_object.get_cutoffs_rating()
print(CutOffs)
for k in range(len(credit_metrics_object.issuer_data)):
    print(credit_metrics_object.issuer_data[k].name)
get_issuer_groups = credit_metrics_object.get_issuer_groups()
print(get_issuer_groups)
# print(EV.index.to_list())

               EV
issuer           
BASF     499969.0
LHA      579720.0
VW      1499460.0
               D          C          B         BB        BBB          A  \
issuer                                                                    
BASF    190000.0   438651.0   483880.0   496714.0   499442.0   499814.0   
LHA     210000.0   522819.0   579720.0   595866.0   599298.0   599766.0   
VW      600000.0  1321890.0  1453200.0  1490460.0  1498380.0  1499460.0   

               AA        AAA  
issuer                        
BASF     499969.0   499969.0  
LHA      599961.0   599961.0  
VW      1499910.0  1499910.0  
Dax     1.000000
BASF    0.865773
LHA     0.613133
VW      0.508473
dtype: float64
[[-3.71902 -3.71902 -3.23888 -2.91124 -2.30440 -1.62576 -0.84915]
 [-3.54008 -3.43161 -3.19465 -2.22621 -2.04151 -1.32431  1.02154]
 [-3.35279 -2.94784 -2.71638 -1.96512 -1.23186  1.45597  1.73806]
 [-3.03567 -2.84796 -2.30085 -1.42071  1.36772  2.41350  2.11301]
 [-2.91124 -2.38240 -1.50704  1.

In [52]:
positions = credit_metrics_object.get_issuer_groups()
correlation = credit_metrics_object.get_correlation()
cutOffs = credit_metrics_object.get_cutoffs_rating()
states = credit_metrics_object.get_states()
EV = credit_metrics_object.get_expected_value()
# n_positions = positions["InstrumentID"].nunique()
issuer_info = positions[["IssuerName", "IssuerID", "Rating", "RatingID"]].drop_duplicates()
Loss = np.zeros((credit_metrics_object.n_simulation, len(issuer_info)))
np.random.seed(credit_metrics_object.seed)

for i in range(0, 5):
    YY = norm.ppf(np.random.rand())
    # rr=c*YY.T
    # rr = YY*self.rho
    for issuer in issuer_info["IssuerName"]:
        # n_positions_issuer = positions['InstrumentID'][positions['IssuerID']==issuer.loc[k,"IssuerID"]].nunique()
        # positions_issuer = positions[positions['IssuerID']==issuer.loc[k,"IssuerID"]]
        # positions_issuer.reset_index(inplace = True, drop = True)
        rho = correlation[issuer]
        rr = YY * rho
        YY_ido = norm.ppf(np.random.rand())
        # corr_idio=np.sqrt((1-(c*c)))
        rr_idio = np.sqrt(1 - (rho**2)) * YY_ido
        # print(rr_idio)
        rr_all = rr + rr_idio
        # print(rr)
        # for j in range (0,n_positions_issuer):
        # rho = correlation[positions.loc[j,'IssuerName']]
        # rr = YY*rho
        # YY_ido = norm.ppf(np.random.rand())
        # #corr_idio=np.sqrt((1-(c*c)))
        # rr_idio=np.sqrt(1-(rho**2))*YY_ido
        # print(j)
        # print(n_positions_issuer)
        # print(positions_issuer)
        # rr_all=rr+rr_idio
        # print(rr_all)
        print(f"Altes Rating: {positions.loc[positions['IssuerName'] == issuer, 'Rating'].values[0]}")
        rating = np.array(rr_all < np.matrix(cutOffs[:, issuer_info.loc[issuer_info["IssuerName"] == issuer, "RatingID"].iloc[0]]).T)
        rate_idx = len(rating) - np.sum(rating, 0)
        print(f"Das neue Rating-Index ist: {rate_idx}")
        col_idx = rate_idx[0].astype(int)
        V_t = states.iloc[states.index.get_loc(issuer), col_idx]  # retrieve the corresponding state value of the exposure
        print(f"V_t: {V_t}")
        # Loss_t = V_t - EV.item(k)
        # print(Loss_t)
        # Loss[i, k] = Loss_t
        # print(j)
        # print(k)
        # print(Loss)

# Portfolio_MC_Loss = np.sum(Loss,1)
# return Loss

Altes Rating: AA
Das neue Rating-Index ist: [6]
V_t: 499969.0
Altes Rating: B
Das neue Rating-Index ist: [4]
V_t: 599298.0
Altes Rating: A
Das neue Rating-Index ist: [5]
V_t: 1499460.0
Altes Rating: AA
Das neue Rating-Index ist: [6]
V_t: 499969.0
Altes Rating: B
Das neue Rating-Index ist: [3]
V_t: 595866.0
Altes Rating: A
Das neue Rating-Index ist: [4]
V_t: 1498380.0
Altes Rating: AA
Das neue Rating-Index ist: [6]
V_t: 499969.0
Altes Rating: B
Das neue Rating-Index ist: [2]
V_t: 579720.0
Altes Rating: A
Das neue Rating-Index ist: [5]
V_t: 1499460.0
Altes Rating: AA
Das neue Rating-Index ist: [6]
V_t: 499969.0
Altes Rating: B
Das neue Rating-Index ist: [2]
V_t: 579720.0
Altes Rating: A
Das neue Rating-Index ist: [5]
V_t: 1499460.0
Altes Rating: AA
Das neue Rating-Index ist: [5]
V_t: 499814.0
Altes Rating: B
Das neue Rating-Index ist: [0]
V_t: 210000.0
Altes Rating: A
Das neue Rating-Index ist: [5]
V_t: 1499460.0


In [21]:
credit_metrics_object.get_portfolio_VaR()

InvalidIndexError: (0, array([6]))

#### Calculate Expected Shortfall

In [ ]:
credit_metrics_object.get_portfolio_ES()

np.float64(262658.63909774437)

#### Display Loss Distribution

In [ ]:
px.histogram(credit_metrics_object.get_Loss_distribution())

# Integration Correlations

In [ ]:
from __future__ import division
import pandas as pd
import numpy as np
from scipy.stats import norm
import sys
import math
from scipy.linalg import sqrtm
from random import seed
from random import random
import plotly.express as px
from pandas_datareader import data as pdr
from datetime import date
import yfinance as yf
#yf.pdr_override()
import rivapy

from numpy.linalg import cholesky

### Get data from yahoo finance for issuer and dax as reference index

In [ ]:
def last_business_day():
    today = pd.Timestamp.today().normalize()
    # Erzeuge eine Serie von Daten bis einschließlich heute
    dates = pd.date_range(end=today, periods=30, freq='B')
    # Der letzte Werktag vor heute ist das letzte Datum in der Serie
    last_bd = dates[-2] if dates[-1] == today else dates[-1]
    last_bd_str = last_bd.strftime('%Y-%m-%d')
    return last_bd_str

# Beispiel: Finde den letzten Werktag vor heute
last_bd = last_business_day()
tickerStrings = ['^GDAXI', 'VOW.DE', 'LHA.DE', 'BAS.DE']
ticker_issuer_mapping = {
    '^GDAXI': 'Dax',
    'VOW.DE': 'VW',
    'LHA.DE': 'LHA',
    'BAS.DE': 'BASF'
}

df_ticker = pd.DataFrame()
for ticker in tickerStrings:
    data = yf.download(ticker, start='2012-03-11', end=last_bd)[['Close']].rename(columns={'Close': ticker})
    data = data.reset_index()
    if df_ticker.empty:
        df_ticker = data
    else:
        df_ticker = df_ticker.merge(data, on='Date', how='left')

df_ticker.rename(columns=ticker_issuer_mapping, inplace=True)
df_ticker = df_ticker.set_axis(['Date'] + list(ticker_issuer_mapping.values()), axis=1, )

C:\Users\Noah Köstner\AppData\Local\Temp\ipykernel_28404\4217465877.py:22: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed
C:\Users\Noah Köstner\AppData\Local\Temp\ipykernel_28404\4217465877.py:22: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed
C:\Users\Noah Köstner\AppData\Local\Temp\ipykernel_28404\4217465877.py:27: PerformanceWarning:

dropping on a non-lexsorted multi-index without a level parameter may impact performance.

C:\Users\Noah Köstner\AppData\Local\Temp\ipykernel_28404\4217465877.py:22: FutureWarning:

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed
C:\Users\Noah Köstner\AppData\Local\Temp\ipykernel_28404\4217465877.py:27: PerformanceWarning:

dropping on a non-lexsorted multi-index witho

### Needed input parameter

In [ ]:
credit_metrics_object.position_data = df_ticker


In [ ]:
credit_metrics_object.Nsim = 100

### Loaded and processed position data

### Calculation of VaR

In [ ]:
var = credit_metrics_object.get_portfolio_VaR()
var

KeyError: 'IssuerID'

### Calculation of loss distribution displayed in histogram

In [ ]:
Loss_distribution = credit_metrics_object.get_Loss_distribution()
px.histogram(Loss_distribution)


In [ ]:
sorted(Loss_distribution)[0:11]

[np.float64(-660784.5),
 np.float64(-404824.49999999994),
 np.float64(-390946.5),
 np.float64(-282663.0),
 np.float64(-277006.5),
 np.float64(-277006.5),
 np.float64(-276844.5),
 np.float64(-276777.0),
 np.float64(-276777.0),
 np.float64(-267016.5),
 np.float64(-260239.5)]

### Calculation of Expected Shortfall

In [ ]:
es = credit_metrics_object.get_portfolio_ES()
es

np.float64(262658.63909774437)